export const overlayList = [
  {
    title: 'Music Video',
    mvTitle: '声',
    artist: 'Mitei',
    director: 'Kohei Yamagami',
    youtubeId: 'kMRS5hkl6WE',
  },
  {
    title: 'Music Video',
    mvTitle: 'スタァ',
    artist: 'melt into the cream',
    director: 'Kohei Yamagami',
    youtubeId: 'n8CYxe93iMA',
  },
  {
    title: 'Music Video',
    mvTitle: 'クローゼット',
    artist: 'dbs',
    director: 'Kohei Yamagami',
    youtubeId: 'gxsqizlOAls',
  },
  {
    title: 'Music Video',
    mvTitle: 'Pirate Ship',
    artist: 'nastylone',
    director: 'Kohei Yamagami',
    youtubeId: 'VYqnXIrtdc0',
  },
  {
    title: 'Music Video',
    mvTitle: '半透明',
    artist: 'ゲネラルパウぜ',
    director: 'Kohei Yamagami & Haruto Koduka',
  },
  {
    title: 'Promotion Video',
    mvTitle: '&',
    artist: '',
    director: 'Kohei Yamagami',
    youtubeId: 'XKOw60Hr_hw',
  },
  {
    title: 'Music Video',
    mvTitle: 'ステーション',
    artist: 'dbs',
    director: 'Kohei Yamagami',
    youtubeId: 'G68eEwTmJnE',
  },
  {
    title: 'Music Video',
    mvTitle: '星',
    artist: 'dbs',
    director: 'Kohei Yamagami',
    youtubeId: 'gxsqizlOAls',
  },
  {
    title: 'Music Video',
    mvTitle: 'アイドル♡最強宣言',
    artist: '佐埜めるの',
    director: 'Toru Ooshima',
    youtubeId: 'qYFCUk99liw',
  },
  {
    title: 'Promotion Video',
    mvTitle: 'mo, de in japan',
    director: 'Toru Ooshima',
  },
  {
    title: 'Promotion Video',
    mvTitle: 'WPT 2024',
    director: 'Kohei Yamagami',
  },
  {
    title: 'Promotion Video',
    mvTitle: '第6回秋川流域花火大会',
  },
]
